version: '2'
services:

  postgres:
    build: ./postgres
    restart: always
    image: rspark-postgres
    ports:
      - "5432:5432"     # Postgres
    volumes:
      - rspark_pgdata:/opt/pg-data

  hadoop:
    build: ./hadoop
    restart: always
    image: rspark-hadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI
    volumes:
      - rspark_hadoopdata:/opt/hadoop

  hive:
    build: ./hive
    restart: always
    image: rspark-hive
    ports:
      - "10000:10000"
    depends_on:
      - hadoop

  rstudio:
    build: ./rstudio
    restart: always
    image: rspark-rstudio
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
      - "4040:4040"     # Spark Web UI
    volumes:
      - rspark_rstudio:/home/rstudio
    depends_on: 
      - hadoop
      - hive

volumes:
  rspark_hadoopdata:
  rspark_rstudio:
  rspark_pgdata:
  rspark_sparkdata:
