version: '2'
services:
  rstudio:
    build: .
    image: sparklyrstudio
    links: 
      - postgres
    ports:
      - "8787:8787" #rstudio webUI
    volumes:
      - ../data/rstudio:/home/rstudio
      - ../willtest:/home/rstudio/tests # TEMPORARY directory of test scripts
      - ../jhtest:/home/rstudio/jhtest # TEMPORARY directory for Dr. Harner module work
  postgres:
      build: ../postgres
      image: jh-postgres
      ports:
        - "5432:5432"
      volumes:
        - ../data/pg-data:/opt/pg-data
